{
 "title": "MLOPS",
 "time": { "from": "2023-01-01T00:00:00.000Z", "to": "2025-05-04T13:40:18.000Z" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 16, "x": 0, "y": 0 },
   "options": {
    "content": "# Twitter sentiment Analysis _ Donal Trump\n\n"
   }
  },
  {
   "title": "Number users",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM tweets LIMIT 50 "
    }
   ]
  },
  {
   "title": "sentiment Distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  \"sentiment\"  AS metric,\r\n  count(*)     AS value\r\nFROM public.tweets\r\nGROUP BY \"sentiment\"\r\nORDER BY value DESC;\r\n"
    }
   ]
  },
  {
   "title": "Average Reply",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(\"replycount\") FROM tweets LIMIT 50 "
    },
    {}
   ]
  },
  {
   "title": "Average Retweet",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(\"retweetcount\") FROM tweets LIMIT 50 "
    }
   ]
  },
  {
   "title": "Average Like",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(\"likecount\") FROM tweets LIMIT 50 "
    }
   ]
  },
  {
   "title": "Average View",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(\"viewcount\") FROM tweets LIMIT 50 "
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  to_date(month_year, 'YYYY-MM') AS time,\r\n  count(*) FILTER (WHERE \"sentiment\" = 'Positive') AS Positive,\r\n  count(*) FILTER (WHERE \"sentiment\" = 'Negative') AS Negative,\r\n  count(*) FILTER (WHERE \"sentiment\" = 'Neutral')  AS Neutral\r\nFROM public.tweets\r\nGROUP BY 1\r\nORDER BY 1;\r\n"
    }
   ]
  }
 ]
}