# MLOPS/dockerfiles/docker-compose.yml
version: '3.8'
services:
  fastapi-serving-app:
    image: pphanhh/mlops-sentiment-server:local-build # Match Docker Hub repo if desired for local tag
    build:
      context: ..  # MLOPS/ root directory
      dockerfile: dockerfiles/dockerfile # Path to Dockerfile from MLOPS/ context
    ports:
      - "5001:5001"
    volumes:
      - ../mlruns:/app/mlruns:ro
      - ../latest_runs.json:/app/artifacts_mount/latest_runs.json:ro
      - ../test_data.csv:/app/artifacts_mount/test_data.csv:ro
      - ../current_champion.json:/app/artifacts_mount/current_champion.json
    environment:
      MLFLOW_TRACKING_PATH_IN_SERVING: "/app/mlruns"
      ARTIFACTS_MOUNT_PATH_IN_SERVING: "/app/artifacts_mount"
      MLFLOW_EXPERIMENT_NAME_SERVING: "sentiment-analysis"
    container_name: my-mlops-fastapi-server-local