# MLOPS/dockerfiles/dockerfile
FROM python:3.10-slim

WORKDIR /app

RUN groupadd -r appuser && useradd -r -g appuser -s /sbin/nologin -c "Docker image user" appuser

COPY dockerfiles/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY model_pipeline/model_serve.py .
# If model_serve.py imports other custom .py files from model_pipeline:
# COPY model_pipeline/your_utility_module.py .

RUN mkdir -p /app/mlruns && chown appuser:appuser /app/mlruns
RUN mkdir -p /app/artifacts_mount && chown appuser:appuser /app/artifacts_mount

USER appuser
EXPOSE 5001
CMD ["uvicorn", "model_serve:app", "--host", "0.0.0.0", "--port", "5001"]