# MLOPS/.github/workflows/deploy_serving_app_dockerhub.yml
name: Deploy FastAPI Serving App to VM via Docker Hub

on:
  push:
    branches: [main]
    paths:
      - 'model_pipeline/model_serve.py'
      # - 'model_pipeline/tests/**'      # If you have tests
      - 'dockerfiles/dockerfile'
      - 'dockerfiles/requirements.txt'
      - '.github/workflows/deploy_serving_app_dockerhub.yml'
  pull_request: # Optional: Run checks on PRs targeting main
    branches: [main]
    paths:
      - 'model_pipeline/model_serve.py'
      # - 'model_pipeline/tests/**'
      - 'dockerfiles/dockerfile'
      - 'dockerfiles/requirements.txt'

env:
  DOCKERHUB_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/mlops-sentiment-server # Your Docker Hub repo name

jobs:
  # Optional: Add a test job if you have tests
  test-serving-app:
    name: Test Serving App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies for app and tests
        run: |
          python -m pip install --upgrade pip
          pip install -r dockerfiles/requirements.txt # App deps
          pip install pytest httpx flake8             # Test/Lint deps
      - name: Lint with flake8
        run: |
                pip install flake8
                flake8 .
      - name: Run Pytests
        run: |
                pip install pytest
                pytest

  build-and-push-to-dockerhub:
    name: Build and Push to Docker Hub
    # needs: test-serving-app # Uncomment if you add the test job
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-push
        uses: docker/build-push-action@v5
        with:
          context: . # Build context is MLOPS/ root
          file: ./dockerfiles/dockerfile # Path to Dockerfile from MLOPS/ root
          push: true
          tags: |
            ${{ env.DOCKERHUB_IMAGE_NAME }}:${{ github.sha }}
            ${{ env.DOCKERHUB_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-to-vm:
    name: Deploy to VM
    needs: build-and-push-to-dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Production VM via SSH
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.PROD_VM_HOST }}
    username: ${{ secrets.PROD_VM_USERNAME }}
    key: ${{ secrets.PROD_VM_SSH_KEY }}
    script: |
      echo "--- Setting up project directories on VM ---"
      mkdir -p /srv/my_mlops_project/MLOPS/mlruns
      touch /srv/my_mlops_project/MLOPS/latest_runs.json
      touch /srv/my_mlops_project/MLOPS/current_champion.json
      touch /srv/my_mlops_project/MLOPS/test_data.csv
      echo "--- Deployment complete ---"